/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academiaweb.interfaces;

import academiaweb.Principal;
import clases.Estudiante;
import clases.Gerente;
import clases.Pais;
import clases.Profesor;
import com.db4o.ObjectSet;
import java.util.ArrayList;
import java.util.Arrays;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validaciones.AcademiaWeb;
import static validaciones.Registro.error;
import static validaciones.Registro.messageError;

/**
 *
 * @author Usuario
 */
public class Registro_Gerente extends javax.swing.JFrame {
    DefaultTableModel regGe=new DefaultTableModel();

    /**
     * Creates new form Registro_Gerente
     */
    
    public Registro_Gerente() {
        initComponents();
        this.setLocationRelativeTo(null);   
    }
    private void setModelo() {
       String[] cabeceraTable = {"Nombre", "Apellido", "Cedula", "Pais", "CORREO" ,"Titulo","Gerencia"};
       regGe.setColumnIdentifiers(cabeceraTable);       
       jTable1.setModel(regGe);
    }
     private void setDatos() {
         Object[] datos = new Object[regGe.getColumnCount()];
         
         for (int j = 0; regGe.getRowCount() > j; j++) {
             regGe.removeRow(0);
         }
         int i = 0;
         regGe.setRowCount(0);
         ArrayList<Gerente> geren = new ArrayList<>();
         Gerente in;
         ObjectSet consultaCedulaGer = AcademiaWeb.Base.get(new Gerente(null, null, null, null, 0, null, null, null, null, null, null));
         for (int j = 0; j < consultaCedulaGer.size(); j++) {
            in = (Gerente) consultaCedulaGer.get(j);
            geren.add(in);
            in = new Gerente();
        }
         for (Gerente aux: geren) {
             datos[0] = aux.getNombre_per();
             datos[1] = aux.getApellido_per();
             datos[2] = aux.getApellido_per();
             datos[3] = aux.getCedula_per();
             datos[4] = aux.getCorreo_per();
             datos[5] = aux.getTitulo_tra();
             datos[6] =aux.getTipo();
             regGe.addRow(datos);
             i++;
         }
         jTable1.setModel(regGe);
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Geren = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Guar = new javax.swing.JButton();
        Sla = new javax.swing.JButton();
        elim = new javax.swing.JButton();
        busc = new javax.swing.JButton();
        jTextNom = new javax.swing.JTextField();
        jTextApell = new javax.swing.JTextField();
        jTextCed = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTexTituj = new javax.swing.JTextField();
        jPassworContra = new javax.swing.JPasswordField();
        jComboPais = new javax.swing.JComboBox<>();
        modi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jTextField1.setText("REGISTRO DE GERENTE");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("NOMBRE:");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("APELLIDO:");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("CEDULA:");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("PAIS:");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("CORREO: ");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("CONTRASEÑA: ");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("TITULO: ");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("TIPO DE GERENCIA: ");

        Geren.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "COMUNICACNIONES", "DIFANCIERA", " " }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Pais", "Correo", "Titulo", "Gerencia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Guar.setBackground(new java.awt.Color(0, 204, 204));
        Guar.setText("Guardar");
        Guar.setAutoscrolls(true);
        Guar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuarActionPerformed(evt);
            }
        });

        Sla.setBackground(new java.awt.Color(0, 204, 204));
        Sla.setText("Salir");
        Sla.setAutoscrolls(true);
        Sla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlaActionPerformed(evt);
            }
        });

        elim.setBackground(new java.awt.Color(0, 204, 204));
        elim.setText("Eliminar");
        elim.setAutoscrolls(true);
        elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimActionPerformed(evt);
            }
        });

        busc.setBackground(new java.awt.Color(0, 204, 204));
        busc.setText("Buscar");
        busc.setAutoscrolls(true);

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });
        jTextNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNomKeyTyped(evt);
            }
        });

        jTextApell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellActionPerformed(evt);
            }
        });
        jTextApell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellKeyTyped(evt);
            }
        });

        jTextCed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCedKeyTyped(evt);
            }
        });

        jTextEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEmailKeyTyped(evt);
            }
        });

        jTexTituj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexTitujActionPerformed(evt);
            }
        });
        jTexTituj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexTitujKeyTyped(evt);
            }
        });

        jPassworContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassworContraKeyTyped(evt);
            }
        });

        jComboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuador", "Colombia ", "Peru", "Argentina", "EEUU", "Mexico" }));

        modi.setBackground(new java.awt.Color(0, 204, 204));
        modi.setText("Modificar");
        modi.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNom))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextCed, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextApell)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Geren, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPassworContra))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTexTituj, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(51, 51, 51)))
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Guar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(elim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modi, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busc, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(Sla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Guar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(busc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jTextApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassworContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jTextCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexTituj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(Geren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elim, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void GuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuarActionPerformed
        // TODO add your handling code here:
                
            String Cedula = jTextCed.getText();
            String Nombre = jTextNom.getText();
            String Apellido = jTextApell.getText();            
            String pais = jComboPais.getSelectedItem().toString();
            String Correo = jTextEmail.getText();
            String Contra= Arrays.toString(jPassworContra.getPassword());
            String Titulo = jTexTituj.getText();
            String Gerente = Geren.getSelectedItem().toString();
            Tabla();
        
        ObjectSet consultaCedulaEst = AcademiaWeb.Base.get(new Estudiante(null, null, Cedula, null, null, null, null ,null));
        ObjectSet consultaCedulaPro = AcademiaWeb.Base.get(new Profesor(null, null, null, null, null, 0, Cedula, null, null, null, null, null));
        ObjectSet consultaCedulaGer = AcademiaWeb.Base.get(new Gerente(null, null, null, null, 0, Cedula, null, null, null, null, null));
        
        if (!(consultaCedulaEst.isEmpty() && consultaCedulaPro.isEmpty() && consultaCedulaGer.isEmpty())) {
            messageError.add("YA EXISTE LA CEDULA");
            error = true;
        }
 
        
        ObjectSet consultaPais = AcademiaWeb.Base.get(new Pais(pais, null, 0, 0));
            
        if (!(consultaPais.isEmpty())) {
            messageError.add("NO EXISTE ESE PAIS");
            error = true;
        }
        
        if (!(Correo.matches("[a-zA-Z0-9]{10,80}"))) {
            messageError.add("CORREO NO VALIDO");
            error = true;
        }
        
            
        
        if (error) {
            JOptionPane.showMessageDialog(null, messageError.get(0));
            
        } else {
            AcademiaWeb.Base.set(new Gerente(Cedula,Nombre,Apellido,pais,Correo,Contra,Titulo,Gerente));
            setDatos();
          }
        



    }//GEN-LAST:event_GuarActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void jTextNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomKeyTyped
        // TODO add your handling code here:
        char aux = evt.getKeyChar();
        
        boolean Mayus = aux >= 65 && aux < 90;
        boolean minus = aux >= 97 && aux < 122;
        boolean ret =aux == 8;
        boolean ent = aux == 13; 
        if (Mayus == false && minus== false && ret==false && ent== false) {
            JOptionPane.showMessageDialog(null, "El dato:\n " + "-> "+evt.getKeyChar()+"<-\n"+"No esta Permitido");
            evt.consume();
        } else if (jTextNom.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextNomKeyTyped

    private void jTextApellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellActionPerformed

    private void jTextApellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellKeyTyped
        // TODO add your handling code here:
        char aux = evt.getKeyChar();
        char aux1 = evt.getKeyChar();
        boolean Mayus = aux >= 65 && aux < 90;
        boolean minus = aux1 >= 97 && aux1 < 122;
        boolean ret =aux == 8;
        boolean ent = aux == 13; 
        if (Mayus == false&& minus ==false && ret== false && ent== false) {
           JOptionPane.showMessageDialog(null, "El dato:\n " + "-> "+evt.getKeyChar()+"<-\n"+"No esta Permitido");
            evt.consume();}
         else if (jTextApell.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextApellKeyTyped

    private void jTextCedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCedKeyTyped
        // TODO add your handling code here:
        char aux = evt.getKeyChar();
        char espa = evt.getKeyChar();
        char aux1 = evt.getKeyChar();
        boolean ced = aux >= 48 && aux < 58;
        boolean esa = espa == 32;
        boolean ret =aux == 8;
        boolean ent = aux == 13; 

        if (ced == false&& esa == false && ret== false && ent== false ) {
            JOptionPane.showMessageDialog(null, "El dato:\n " + "-> "+evt.getKeyChar()+"<-\n"+"No esta Permitido");
            evt.consume();
        } else if (jTextCed.getText().length() > 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextCedKeyTyped

    private void jTextEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmailKeyTyped
        // TODO add your handling code here:
        char aux = evt.getKeyChar();
        boolean cor = aux >= 64 && aux < 90;
        boolean cor2 = aux >= 97 && aux < 122;
        boolean car = aux == 65;
        boolean ret =aux == 8;
        boolean ent = aux == 13; 
        if (cor == false&& cor2== false && car == false && ret == false && ent== false) {
            JOptionPane.showMessageDialog(null, "El dato:\n " + "-> "+evt.getKeyChar()+"<-\n"+"No esta Permitido");
            evt.consume();
        } else if (jTextEmail.getText().length() > 20) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextEmailKeyTyped

    private void jTexTitujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexTitujActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTexTitujActionPerformed

    private void jTexTitujKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexTitujKeyTyped
        // TODO add your handling code here:
        char aux = evt.getKeyChar();
        boolean ret =aux == 8 && aux == 13;
        boolean Tit = aux >= 64 && aux < 90;
        boolean tit = aux >= 97 && aux < 122;
        boolean ent = aux == 13; 
        if (jTexTituj.getText().length() > 20) {
            evt.consume();
        } else if (Tit == false && tit == false && ret == false && ent== false) {
            JOptionPane.showMessageDialog(null, "El dato:\n " + "-> "+evt.getKeyChar()+"<-\n"+"No esta Permitido");
            evt.consume();
        } 
    }//GEN-LAST:event_jTexTitujKeyTyped

    private void jPassworContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassworContraKeyTyped
        // TODO add your handling code here:
        char aux = evt.getKeyChar();
        boolean con= aux >= 32&& aux< 126;
        boolean ret =aux == 127;
        boolean ent = aux == 10; 
        if(jPassworContra.getText().length()> 25 && ent== false){
            evt.consume();
        }      
        else if (con== false && ret == false ){
            JOptionPane.showMessageDialog(null, "El dato:\n " + "-> "+evt.getKeyChar()+"<-\n"+"No esta Permitido");
            evt.consume();
        }
    }//GEN-LAST:event_jPassworContraKeyTyped

    private void SlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlaActionPerformed
        // TODO add your handling code here:
        dispose();
        Principal pri=new Principal();
        pri.setVisible(true);
    }//GEN-LAST:event_SlaActionPerformed

    private void elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_elimActionPerformed

    public  void Tabla(){
        while(regGe.getRowCount()>0){
            regGe.removeRow(0);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Geren;
    private javax.swing.JButton Guar;
    private javax.swing.JButton Sla;
    private javax.swing.JButton busc;
    private javax.swing.JButton elim;
    private javax.swing.JComboBox<String> jComboPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassworContra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTexTituj;
    private javax.swing.JTextField jTextApell;
    private javax.swing.JTextField jTextCed;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JButton modi;
    // End of variables declaration//GEN-END:variables
}
