/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini.proyecto;

import clases.Certifica;
import clases.Curso;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mini.proyecto.Certificado.Cerrar_BD;

/**
 *
 * @author jose
 */
public class RegistroCurso extends javax.swing.JFrame {

    private String cod_cur;
    private String nombre_cur;
    private String duracion;
    private double precio;
    private String silabo;
    private String deescripcion;
    private String id_pro;
    private String cod_car;;
    
    
    public RegistroCurso() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtduracion = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtcc = new javax.swing.JTextField();
        txtidp = new javax.swing.JTextField();
        txtsilabo = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Insertar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        txtfila = new javax.swing.JTextField();
        EliminarTodo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcolumna = new javax.swing.JTextField();
        txtnd = new javax.swing.JTextField();
        txtconsultar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Registro de datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Codigo Curso:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Ingresar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Nombre del Curso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Duracion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Precio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Silabo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Descripcion:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Codigo Carrera");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("ID Profesor:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, -1));
        jPanel1.add(txtduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, -1));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, -1));

        txtcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtccKeyTyped(evt);
            }
        });
        jPanel1.add(txtcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 90, -1));

        txtidp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidpKeyTyped(evt);
            }
        });
        jPanel1.add(txtidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 90, -1));
        jPanel1.add(txtsilabo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 360, 20));
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 360, 50));

        tabla.setBackground(new java.awt.Color(153, 153, 153));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo curso", "Nombre curso", "Duracion", "Precio", "Codigo carrera", "ID_Profesor", "Silabo", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 800, 110));

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        jPanel1.add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        Consultar.setText("Consular");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));
        jPanel1.add(txtfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 50, -1));

        EliminarTodo.setText("Eliminar todo");
        EliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Fila:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Columna:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Nuevo Dato:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));
        jPanel1.add(txtcolumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 50, -1));
        jPanel1.add(txtnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 120, -1));
        jPanel1.add(txtconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 120, -1));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setText("Menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        
        char aux = evt.getKeyChar();
        boolean numeros = aux>= '0' && aux <= '9';
        if (!numeros){
            JOptionPane.showMessageDialog(this,"CARACTER INCORRECTO: "+evt.getKeyChar());
            evt.consume();
        }else if(txtcodigo.getText().length()>=4){
            evt.consume();
        }
        
        
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtccKeyTyped
char aux = evt.getKeyChar();
        boolean numeros = aux>= '0' && aux <= '9';
        if (!numeros){
            JOptionPane.showMessageDialog(this,"CARACTER INCORRECTO: "+evt.getKeyChar());
            evt.consume();
        }else if(txtcc.getText().length()>=4){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtccKeyTyped

    private void txtidpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpKeyTyped

        // TODO add your handling code here:
        
        char aux = evt.getKeyChar();
        boolean numeros = aux>= '0' && aux <= '9';
        if (!numeros){
            JOptionPane.showMessageDialog(this,"CARACTER INCORRECTO: "+evt.getKeyChar());
            evt.consume();
        }else if(txtidp.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_txtidpKeyTyped

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
 ObjectContainer BaseD = Db4o.openFile("E:\\Proyecto final Base de datos\\Mini-Proyecto\\MiniProyecto");
        Crear_Curso(BaseD);
        Cerrar_BD(BaseD)        
        
    }//GEN-LAST:event_InsertarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
   
    }//GEN-LAST:event_EliminarActionPerformed

    private void EliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodoActionPerformed
                
    }//GEN-LAST:event_EliminarTodoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
      
    }//GEN-LAST:event_ModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MiniProyecto regresar = new MiniProyecto();
        regresar.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Interfaz_curso regresar = new Interfaz_curso();
        regresar.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarActionPerformed
       public void Crear_Curso(ObjectContainer basep) {
        asignarVariables(basep);
       
            if (Comprobar_Curso(basep, cod_cur) == 0) {
                Curso ncurso= new Curso(cod_cur, nombre_cur, duracion,  precio,silabo,deescripcion,id_pro,cod_car);
                basep.set(ncurso);
                JOptionPane.showMessageDialog(null, "Curso registrado correctamente");
                LimpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "El curso ya existe", "ERROR", 0);
//                JOptionPane.showMessageDialog(this, "La asignatura ya existe");
            }
        
    }
       public static int Comprobar_Curso(ObjectContainer basep, String cod_cer) {
        Curso bcurso = new Curso(cod_cur, null, null,null,null,null.null.null);
        ObjectSet result = basep.get(bcurso);
        return result.size();
    }
     public void asignarVariables(ObjectContainer basep) {
        cod_cur = txtcodigo.getText();
        nombre_cur = txtnombre.getText();
        duracion = txtduracion.getText();
        //precio = txtprecio.getDouble();
        silabo = txtsilabo.getText();
        deescripcion = txtdescripcion.getText();
        id_pro = txtidp.getText();
        cod_car = txtcc.getText();
    }
    
    
    public void LimpiarCampos() {
        txtcodigo.setText("");
        txtnombre.setText("");
        txtduracion.setText("");
        txtsilabo.setText("");
        txtdescripcion.setText("");
        txtidp.setText("");
        txtcc.setText("");
    }
    //////////////////////////////////////////////////////////////////////////////////////////////////////Eliminar
   
    
    public static void Cerrar_BD(ObjectContainer basep) {
        basep.close();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton EliminarTodo;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtcc;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcolumna;
    private javax.swing.JTextField txtconsultar;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtduracion;
    private javax.swing.JTextField txtfila;
    private javax.swing.JTextField txtidp;
    private javax.swing.JTextField txtnd;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtsilabo;
    // End of variables declaration//GEN-END:variables
}
